import Sofa
import SofaSubmission.Solution
/-! Axiom audit.  Run: `lake env lean Sofa/Check.lean`.
Expected for every line: a subset of `[propext, Classical.choice, Quot.sound]` (no `sorryAx`),
including the main theorem and the four upstream statements (the last lines).  Check with
`lake env lean Sofa/Check.lean > check.txt; echo $?; grep -c sorryAx check.txt; tail -6 check.txt`
(expected: `0`, `0`, and six lines ending in `[propext, Classical.choice, Quot.sound]`). -/
-- M1
#print axioms MovingSofa.sofaConstant_le_two_mul_sqrt_two
#print axioms MovingSofa.sofaConstant_ne_top
#print axioms Sofa.hallway_eq_diff
#print axioms Sofa.suppHallway_eq
#print axioms Sofa.subset_suppHallway
#print axioms Sofa.rot_eq_rotation
-- M2
#print axioms Sofa.exists_rotationAngle
#print axioms Sofa.continuous_supportFn
#print axioms MovingSofa.IsMovingSofa.isBounded
#print axioms MovingSofa.IsMovingSofa.subset_suppHallway
#print axioms MovingSofa.IsMovingSofa.subset_monotoneHull
#print axioms Sofa.continuous_motion_of_continuous_apply
-- M-H
#print axioms Sofa.isMovingSofa_hammersleySofa
#print axioms MovingSofa.pi_div_two_add_two_div_pi_le_sofaConstant
#print axioms MovingSofa.ofReal_two_point_two_lt_sofaConstant
-- M2 batch 3–4 (Baek §2.3–2.4, Thm 1.5.1)
#print axioms Sofa.stdPos_tr_stdVec
#print axioms Sofa.IsSofaWithAngle.subset
#print axioms Sofa.isConnected_Imono
#print axioms Sofa.isSofaWithAngle_of_subset_suppHallway
#print axioms Sofa.IsSofaWithAngle.Imono_props
#print axioms Sofa.IsSofaWithAngle.isCap_Ccap
#print axioms Sofa.IsSofaWithAngle.Imono_eq_Ccap_sdiff
#print axioms Sofa.IsMonotoneSofa.eq_Ccap_sdiff_niche
#print axioms Sofa.IsSofaWithAngle.Imono_Imono
#print axioms Sofa.IsSofaWithAngle.eq_Imono_iff
#print axioms Sofa.exists_rotationAngle_mem_of_volume_ge
-- M2 batch 5 (Baek §2.5, part 1)
#print axioms Sofa.niche_eq_iUnion_wedge
#print axioms Sofa.IsCap.cornerA_mem
#print axioms Sofa.IsCap.cornerC_mem
#print axioms Sofa.IsCap.gapW_pos
#print axioms Sofa.IsCap.gapZ_pos
#print axioms Sofa.IsCap.mem_of_bottom
#print axioms Sofa.IsCap.wedge_subset
#print axioms Sofa.IsCap.cornerA_not_mem_niche
#print axioms Sofa.IsCap.cornerC_not_mem_niche
-- M2 batch 6 (Baek §2.5, part 2)
#print axioms Sofa.isOpen_setOf_edge_subset
#print axioms Sofa.IsCap.isConnected_upperBdry
#print axioms Sofa.IsCap.upperBdry_eq_relFrontier
#print axioms Sofa.IsCap.tfae_niche_subset
#print axioms Sofa.IsCap.niche_subset_iff
#print axioms Sofa.IsMonotoneSofa.volume_eq
#print axioms Sofa.IsMonotoneSofa.sofaArea_Ccap
-- M3a (vertices, Thm 2.1.3)
#print axioms Sofa.edge_eq_segment
#print axioms Sofa.tendsto_vtxP_right
#print axioms Sofa.tendsto_vtxM_right
#print axioms Sofa.tendsto_vtxP_left
#print axioms Sofa.tendsto_vtxM_left
#print axioms Sofa.tendsto_vtx2_right
#print axioms Sofa.tendsto_vtx2_left
#print axioms Sofa.hasDerivWithinAt_supportFn_Ioi
#print axioms Sofa.hasDerivWithinAt_supportFn_Iio
-- M3a (mirror symmetry, Hausdorff distance)
#print axioms Sofa.volume_mirror_image
#print axioms Sofa.niche_mirror
#print axioms Sofa.IsCap.image_mirror
#print axioms Sofa.vtxP_mirror
#print axioms Sofa.wedge_mirror
#print axioms Sofa.IsCap.cornerA_mirror
#print axioms Sofa.abs_supportFn_sub_le_hausdorffDist
#print axioms Sofa.subset_of_tendsto_hausdorffDist
#print axioms Sofa.exists_tendsto_hausdorffDist
#print axioms Sofa.mem_of_closedBall_subset
-- M3a/M3b definitions and the final assembly
#print axioms Sofa.IsCap.isBounded_niche
#print axioms Sofa.IsCap.sofaArea_le_polySofaArea
-- M3b: Nef sets and the area derivative (replaces Thm 3.1.2)
#print axioms Sofa.volume_eq_lintegral_slice
#print axioms Sofa.measurableSet_nefSet
#print axioms Sofa.volume_slice_symmDiff_le
#print axioms Sofa.volume_pushed_sdiff
#print axioms Sofa.hasDerivWithinAt_volume_pushed
-- M3b: piecewise-affine calculus (G1) and the graph representation of `C_Θ`, `N_Θ`
#print axioms Sofa.sub_eq_sum_mul_measureReal_activeSet
#print axioms Sofa.sum_volume_activeSet_inter
#print axioms Sofa.volume_between_Icc
#print axioms Sofa.polyCap_eq_capH
#print axioms Sofa.polyNiche_eq_nicheH
#print axioms Sofa.polySofaArea_eq_areaH
-- M3b: the area derivative (G2) and the balance identity (G3)
#print axioms Sofa.hasDerivAt_areaH_push
#print axioms Sofa.sum_sigmaH_sub_tauH
#print axioms Sofa.exists_tauH_lt_sigmaH
-- M3b: Chapter 3 §3.3–3.4
#print axioms Sofa.isPolyCap_capH
#print axioms Sofa.areaH_transH
#print axioms Sofa.areaH_le_areaH_supportFn
#print axioms Sofa.posR_subset_posU
#print axioms Sofa.exists_isPolyCap_push
#print axioms Sofa.IsMaxPolyCap.balanced
#print axioms Sofa.measureReal_activeSet_gfn
#print axioms Sofa.polyNiche_subset_of_balanced
#print axioms Sofa.oω_mem
#print axioms Sofa.width_le_of_area_nonneg
#print axioms Sofa.tendsto_areaH_of_tendsto
#print axioms Sofa.exists_isMaxPolyCap
-- M3b: Chapter 3 §3.5
#print axioms Sofa.quarter_le_polySofaArea_one
#print axioms Sofa.le_volume_of_tendsto_hausdorffDist
#print axioms Sofa.eventually_volume_le_of_tendsto_hausdorffDist
#print axioms Sofa.eventually_le_volume_of_eventually_mem
#print axioms Sofa.isCap_of_tendsto
#print axioms Sofa.exists_mem_uniformAngles
#print axioms Sofa.eventually_mem_polyNiche
#print axioms Sofa.isPolyCap_polyCap
#print axioms Sofa.supportFn_polyCap
#print axioms Sofa.exists_isBalancedMaxCap
#print axioms Sofa.IsBalancedMaxCap.niche_subset
#print axioms Sofa.IsBalancedMaxCap.isMax
-- M4: Chapter 4 §4.1
#print axioms Sofa.gapWinf_mirror
#print axioms Sofa.gapWinf_le_supportFn_zero
#print axioms Sofa.abs_gapW_sub_gapW_le
#print axioms Sofa.gapWinf_sub_le_gapWinf
#print axioms Sofa.actF_pi_div_two
#print axioms Sofa.gapWinf_le_tauH
#print axioms Sofa.supportFn_left_le
#print axioms Sofa.pt_one_mem_of_mem_Icc
#print axioms Sofa.IsMaxPolyCap.mem_top_segment
#print axioms Sofa.IsBalancedMaxCap.oω_mem
#print axioms Sofa.IsBalancedMaxCap.mem_top_segment
-- M4: Chapter 4 §4.2
#print axioms Sofa.measureReal_between_restrict
#print axioms Sofa.measureReal_para_gt
#print axioms Sofa.measureReal_para_le_cw
#print axioms Sofa.measureReal_para
#print axioms Sofa.measureReal_le_of_supportFn_lt
#print axioms Sofa.dmin_mul_cos_le_sin
#print axioms Sofa.measureReal_lt_of_supportFn_lt
#print axioms Sofa.one_lt_dmin_mul_sin
#print axioms Sofa.dmin_ineq
#print axioms Sofa.sub_mem_uniformAngles
#print axioms Sofa.IsPolyCap.image_mirror
#print axioms Sofa.IsMaxPolyCap.image_mirror
#print axioms Sofa.IsBalancedMaxCap.image_mirror
#print axioms Sofa.le_gapWinf_of_sq
#print axioms Sofa.wedge_right
#print axioms Sofa.exists_wedge
-- M4: the geometric input to Thm 1.5.2
#print axioms Sofa.inner_eq_coord
#print axioms Sofa.mem_niche_of_coord_lt
#print axioms Sofa.width_le_one
#print axioms Sofa.cw_le_coord_of_not_mem_niche
#print axioms Sofa.inner_sub_le_one_of_subset
#print axioms Sofa.supportFn_add_supportFn_le_one
-- M4: Theorem 1.5.2 (the movement) and interface (I2)
#print axioms Sofa.supportFn_rot_image
#print axioms Sofa.rigid_apply
#print axioms Sofa.continuous_rigid
#print axioms Sofa.coord_rot_add_zero
#print axioms Sofa.coord_rot_add_one
#print axioms Sofa.isSofaWithAngle_rot_image
#print axioms Sofa.volume_rot_image
#print axioms Sofa.IsBalancedMaxCap.exists_monotoneSofa_pi_div_two
-- M5: Chapter 5 — the surface area measure
#print axioms Sofa.monotone_of_locally
#print axioms Sofa.cos_mul_inner_vtxP_sub_le
#print axioms Sofa.inner_vtxP_sub_v_nonneg
#print axioms Sofa.inner_vtxP_sub_u_le_tan
#print axioms Sofa.arcFn_mono
#print axioms Sofa.arcFn_right_continuous
#print axioms Sofa.sigmaK_Ioc
#print axioms Sofa.sigmaK_singleton
#print axioms Sofa.inner_vtxP_sub_v_le_arcFn
#print axioms Sofa.arcFn_sub_le
#print axioms Sofa.abs_inner_v_sub_le
#print axioms Sofa.abs_defect_le
#print axioms Sofa.inner_vtxP_sub_eq_setIntegral
#print axioms Sofa.vtxP_sub_eq_setIntegral
-- M6: Chapter 6 §6.2 — arm lengths
#print axioms Sofa.outerCorner_eq_vtxP_add
#print axioms Sofa.outerCorner_eq_vtxP_add'
#print axioms Sofa.armGp_eq_setIntegral
#print axioms Sofa.intervalIntegrable_edgeMax
#print axioms Sofa.supportFn_sub_eq_intervalIntegral
#print axioms Sofa.armGp_eq_add
#print axioms Sofa.sigmaK_Ioc_toReal_eq
#print axioms Sofa.hasDerivAt_u
#print axioms Sofa.hasDerivAt_v
#print axioms Sofa.hasDerivWithinAt_outerCorner
#print axioms Sofa.hasDerivWithinAt_innerCorner
-- M6: Chapter 6 §6.1, Def 6.3.4
#print axioms Sofa.IsInjectiveCap.inner_deriv_innerCorner
#print axioms Sofa.m0_mono
#print axioms Sofa.m0_of_le_one
#print axioms Sofa.m0_of_mem_Icc_one_two
#print axioms Sofa.m0_of_two_le
#print axioms Sofa.m0_le_one
-- M6: weak convergence of the surface area measures
#print axioms Sofa.edge_eq_singleton
#print axioms Sofa.exists_hausdorffDist_edge_subset_ball
#print axioms Sofa.tendsto_vtxP_of_tendsto_hausdorffDist
#print axioms Sofa.tendsto_edgeMax_of_tendsto_hausdorffDist
#print axioms Sofa.tendsto_primitive_of_tendsto_hausdorffDist
#print axioms Sofa.tendsto_arcFn_of_tendsto_hausdorffDist
#print axioms Sofa.tendsto_sigmaK_Ioc
-- M7: the area of a plane triangle (the atom for Thm 7.1.3)
#print axioms Sofa.volume_stdTri
#print axioms Sofa.det_triLin
#print axioms Sofa.volume_tri
#print axioms Sofa.measureReal_tri
#print axioms Sofa.measureReal_triAt
#print axioms Sofa.tri_subset_of_convex
#print axioms Sofa.cross_nonneg_of_mem_tri
#print axioms Sofa.cross_cramer
#print axioms Sofa.exists_smul_of_cross_eq_zero
#print axioms Sofa.wedgeC_subset_left
#print axioms Sofa.wedgeC_subset_right
#print axioms Sofa.volume_setOf_cross_eq_zero
#print axioms Sofa.volume_sector_add
#print axioms Sofa.cross_eq_frame
#print axioms Sofa.abs_cross_vtxP_sub_le
#print axioms Sofa.mem_wedgeC_decomp
#print axioms Sofa.sector_subset_tri_smul
#print axioms Sofa.volume_sector_squeeze
#print axioms Sofa.vtxP_eq_of_arcFn_eq
#print axioms Sofa.cross_vtxP_nonneg
-- M7: Thm 7.1.3 — the local identity `|sector| = ½∫ h dσ`
#print axioms Sofa.curveG_add
#print axioms Sofa.abs_curveG_sub_le
#print axioms Sofa.secR_add
#print axioms Sofa.secR_eq_zero_of_arcFn_eq
#print axioms Sofa.local_geom
#print axioms Sofa.cross_vtxP_pos_of
#print axioms Sofa.abs_secR_sub_curveG_le
#print axioms Sofa.secR_add'
#print axioms Sofa.secR_eq_curveG
-- M7b: the angular order of the vertex map (step 5(d) of Thm 7.1.3)
#print axioms Sofa.vtxP_add_two_pi
#print axioms Sofa.inner_vtxP_mono
#print axioms Sofa.inner_vtxP_anti
#print axioms Sofa.inner_vtxP_frame
#print axioms Sofa.inner_vtxP_pos_near
#print axioms Sofa.inner_vtxP_neg_near
-- M7c: the wedge tiling and Thm 7.1.3 (`|K| = ½ ∫ h_K dσ_K`)
#print axioms Sofa.exists_angle
#print axioms Sofa.exists_polar_Ico
#print axioms Sofa.sin_sandwich
#print axioms Sofa.vtxP_eq_polar
#print axioms Sofa.vtxAngle_add_two_pi
#print axioms Sofa.vtxAngle_step
#print axioms Sofa.angle_mem_of_mem_wedgeC
#print axioms Sofa.exists_mem_wedgeC
#print axioms Sofa.eq_iUnion_sector
#print axioms Sofa.sector_aeDisjoint
#print axioms Sofa.volume_eq_sum_sector
#print axioms Sofa.volumeReal_eq_sum_secR
#print axioms Sofa.volumeReal_eq_curveG_of_part
#print axioms Sofa.volumeReal_eq_curveG
-- M7d: Thm 7.1.3 for an arbitrary convex body (translation covariance)
#print axioms Sofa.vtxP_tr
#print axioms Sofa.arcFn_tr
#print axioms Sofa.sigmaK_tr
#print axioms Sofa.setIntegral_inner_u_sigmaK
#print axioms Sofa.curveG_tr
#print axioms Sofa.exists_areaSetup_of_mem_interior
#print axioms Sofa.volumeReal_eq_curveG_of_mem_interior
#print axioms Sofa.volumeReal_eq_curveG_of_interior_nonempty
-- M8: Baek §7.1 — convex domains, quadratic functionals, and `|K|` as one
#print axioms Sofa.ConvexBilinearOn.expand
#print axioms Sofa.quad_along
#print axioms Sofa.dirDeriv_eq
#print axioms Sofa.isMaxOn_iff_dirDeriv_nonpos
#print axioms Sofa.supportFn_mix
#print axioms Sofa.vtxP_mix
#print axioms Sofa.edgeMax_mix
#print axioms Sofa.arcFn_mix
#print axioms Sofa.sigmaK_mix
#print axioms Sofa.areaB_mix_left
#print axioms Sofa.areaB_mix_right
#print axioms Sofa.isQuadraticOn_volumeReal
-- M6b: Baek §6.5 — bounding the arm lengths (conditional on Thm 6.5.1)
#print axioms Sofa.continuous_m0
#print axioms Sofa.armF_mono
#print axioms Sofa.jFn_le_armF
#print axioms Sofa.armIter_one
#print axioms Sofa.one_lt_armIter_eleven
#print axioms Sofa.armIter_le_of_armPair
#print axioms Sofa.one_lt_of_armPair
-- M6c: the geometric core of Baek Thm 6.3.3 (`Sofa/NicheBound.lean`)
#print axioms Sofa.lineFn_le_lineFn_iff
#print axioms Sofa.setOf_lineFn_le_pos
#print axioms Sofa.setOf_lineFn_le_neg
#print axioms Sofa.volume_setOf_lineFn_eq
#print axioms Sofa.actR_subset_pieces
#print axioms Sofa.volume_crossSet
#print axioms Sofa.pieceL_eq
#print axioms Sofa.pieceR_eq
#print axioms Sofa.pieceS_eq
#print axioms Sofa.volumeReal_subset_actR_le
#print axioms Sofa.pieceU_eq
#print axioms Sofa.sigmaH_le_lenU
#print axioms Sofa.tauH_eq_pi_div_two
#print axioms Sofa.edgeMax_le
#print axioms Sofa.le_edgeMin
#print axioms Sofa.lenL_le
#print axioms Sofa.lenR_le
#print axioms Sofa.thm633_arith
#print axioms Sofa.sigmaH_le_k0_armGp
#print axioms Sofa.tan_le_add_cube
#print axioms Sofa.thalf_le_add_cube
#print axioms Sofa.sigmaH_le_k0_delta
#print axioms Sofa.ofReal_edgeLength_mul_sin_le
#print axioms Sofa.edgeLength_le_sigmaH
#print axioms Sofa.edgeLength_le_k0_delta
#print axioms Sofa.sigmaK_singleton_le_k0_delta
#print axioms Sofa.u_frame
#print axioms Sofa.edgeLength_eq_zero_of_no_normal
#print axioms Sofa.volume_setOf_inner_eq
#print axioms Sofa.width_pos_of_volume_ne_zero
#print axioms Sofa.vtxP_mem_vtx2_image
#print axioms Sofa.const_of_continuousOn_of_finite_image
#print axioms Sofa.continuousOn_vtxP_gap
#print axioms Sofa.vtxP_const_on_gap
#print axioms Sofa.sigmaK_gap_eq_zero
-- round 21: §6.4 (Lemma 6.4.1, Lemma 6.4.2, Equations (6.4)/(6.5))
#print axioms Sofa.k0_eq_abs
#print axioms Sofa.k0_le_add_abs
#print axioms Sofa.abs_k0_sub_le
#print axioms Sofa.lipschitzWith_k0
#print axioms Sofa.continuous_k0
#print axioms Sofa.intervalIntegrable_armGp
#print axioms Sofa.intervalIntegrable_k0_comp
#print axioms Sofa.vtxP_const_on_Ico_gap
#print axioms Sofa.arcFn_const_on_Ico_gap
#print axioms Sofa.armGp_eq_sub_inner
#print axioms Sofa.abs_armGp_sub_le_gap
#print axioms Sofa.abs_integral_k0_armGp_sub_le
#print axioms Sofa.k0_armGp_mul_le_integral
#print axioms Sofa.edgeMax_sub_edgeMin
#print axioms Sofa.tendsto_arcFn_nhdsLT
#print axioms Sofa.countable_edgeLength_ne_zero
#print axioms Sofa.abs_edgeMax_le
#print axioms Sofa.abs_armGp_le
#print axioms Sofa.k0_le_one_add_abs
#print axioms Sofa.tendsto_supportFn_of_tendsto_hausdorffDist
#print axioms Sofa.tendsto_armGp_of_tendsto_hausdorffDist
#print axioms Sofa.tendsto_integral_k0_armGp
#print axioms Sofa.measure_Ioc_le_sum
#print axioms Sofa.sigmaK_Ioc_le_integral_of_steps
#print axioms Sofa.integral_k0_armGp_shift_le
#print axioms Sofa.sigmaK_Ioc_eq_singleton_of_gap
#print axioms Sofa.sigmaK_Ioc_le_integral_of_limit
#print axioms Sofa.sigmaK_Ioc_le_integral_of_limit'
#print axioms Sofa.integral_k0_armGp_widen_le
#print axioms Sofa.u_ne_u_of_sub_lt
#print axioms Sofa.mem_polyCapFin
#print axioms Sofa.coe_polyCapFin
#print axioms Sofa.IsPolyCap.eq_iInter_fin
#print axioms Sofa.mem_uniformAngles_iff
#print axioms Sofa.uniform_gap_base
#print axioms Sofa.uniform_gap_shift
#print axioms Sofa.sigmaK_step_le_integral
#print axioms Sofa.sigmaK_Ioc_le_integral_poly
-- round 22: Theorem 6.4.3 and Theorem 6.5.1 for balanced maximum caps
#print axioms Sofa.exists_eventually_norm_le
#print axioms Sofa.tendsto_arcFn_nhdsGT
#print axioms Sofa.volume_ne_zero_of_isMaxPolyCap
#print axioms Sofa.width_pos_of_isMaxPolyCap
#print axioms Sofa.exists_dyadic_sandwich
#print axioms Sofa.sigmaK_Ioc_le_integral_dyadic
#print axioms Sofa.sigmaK_Ioc_le_integral_balanced
#print axioms Sofa.sigmaK_Ioc_zero_le_integral
#print axioms Sofa.armFp_ge_balanced
-- round 23: `σ_K` has no atoms in `(0, π/2)` (Cor 6.4.4 without Radon–Nikodym)
#print axioms Sofa.edgeLength_eq_zero_of_balanced
#print axioms Sofa.sigmaK_Ioc_le_integral_balanced'
#print axioms Sofa.sigmaK_Ioc_zero_le_integral'
-- round 24: Prop 6.2.2 (mirror), the mirror of a balanced maximum cap, and Thm 6.5.1 for it
#print axioms Sofa.mirror_u_eq
#print axioms Sofa.mirror_v_eq
#print axioms Sofa.mirror_neg
#print axioms Sofa.mirror_sub
#print axioms Sofa.outerCorner_mirror
#print axioms Sofa.armFp_mirror
#print axioms Sofa.armGp_mirror
#print axioms Sofa.oω_pi_div_two
#print axioms Sofa.mirror_oω_pi_div_two
#print axioms Sofa.mirror_oω_le
#print axioms Sofa.IsMaxPolyCap.image_mirror_le
#print axioms Sofa.IsBalancedMaxCap.image_mirror_le
#print axioms Sofa.edgeLength_eq_zero_of_balanced_upper
#print axioms Sofa.armFm_eq_armFp_of_balanced
#print axioms Sofa.armGm_eq_armGp_of_balanced
#print axioms Sofa.armFp_nonneg
#print axioms Sofa.armFm_nonneg
#print axioms Sofa.armGp_nonneg
#print axioms Sofa.armGm_nonneg
#print axioms Sofa.armGm_ge_balanced
-- round 25: the endpoint-angle bound, `σ_K({0}) = 0`, and `f⁺_K(0) = 1`
#print axioms Sofa.inner_v_zero_nonneg
#print axioms Sofa.edgeMin_zero_of_isCap
#print axioms Sofa.armFm_zero_of_isCap
#print axioms Sofa.armFp_zero_eq
#print axioms Sofa.actR_subset_cross_or_le
#print axioms Sofa.tauH_le_crude
#print axioms Sofa.edgeLength_le_crude
#print axioms Sofa.uniform_no_normal_zero
#print axioms Sofa.edgeLength_zero_of_maxPolyCap
#print axioms Sofa.arcFn_zero_of_maxPolyCap
#print axioms Sofa.edgeLength_delta_le
#print axioms Sofa.arcFn_le_of_maxPolyCap
#print axioms Sofa.edgeLength_zero_of_balanced
#print axioms Sofa.armFp_zero_of_balanced
#print axioms Sofa.one_add_integral_le_armFp
-- round 26: the `ArmPair` package and Theorem 6.5.6 (`f_K, g_K > 1`)
#print axioms Sofa.armFm_mirror
#print axioms Sofa.edgeLength_eq_zero_Ico
#print axioms Sofa.vtxM_eq_vtxP_Ico
#print axioms Sofa.continuousOn_vtxM_Icc
#print axioms Sofa.continuousOn_armFm_Icc
#print axioms Sofa.clamp_mem
#print axioms Sofa.continuous_clamp
#print axioms Sofa.continuous_armFK
#print axioms Sofa.armFK_nonneg
#print axioms Sofa.armFK_of_mem
#print axioms Sofa.armFK_zero
#print axioms Sofa.armFK_eq_armFp
#print axioms Sofa.armFK_mirror_sub
#print axioms Sofa.intervalIntegrable_m0_armGp
#print axioms Sofa.integral_armFK_mirror
#print axioms Sofa.tendsto_armFm_nhdsLT
#print axioms Sofa.armFK_bound
#print axioms Sofa.armPair_balanced
#print axioms Sofa.one_lt_armFp_of_balanced
#print axioms Sofa.one_lt_armGp_of_balanced
#print axioms Sofa.continuousOn_armGp_Icc
#print axioms Sofa.continuousOn_armFp_Ico
-- round 27: absolute continuity of `σ_K` and **Theorem 6.1.1**
#print axioms Sofa.clamp_le_clamp
#print axioms Sofa.clamp_sub_le
#print axioms Sofa.clamp_mem_Icc
#print axioms Sofa.clampSF
#print axioms Sofa.lipDiffSF
#print axioms Sofa.clampSF_measure_le
#print axioms Sofa.sigmaK_restrict_eq_clampSF
#print axioms Sofa.sigmaK_restrict_ac
#print axioms Sofa.exists_radius
#print axioms Sofa.arcFn_lip_left
#print axioms Sofa.sigmaK_restrict_ac_left
#print axioms Sofa.sigmaK_ac_left
#print axioms Sofa.arcFn_mirror_eq
#print axioms Sofa.edgeLength_pi_of_balanced
#print axioms Sofa.edgeMax_eq_edgeMin_upper
#print axioms Sofa.arcFn_sub_eq_mirror
#print axioms Sofa.arcFn_lip_right
#print axioms Sofa.sigmaK_ac_right
#print axioms Sofa.exists_density_of_ac
#print axioms Sofa.exists_densities_of_balanced
#print axioms Sofa.isInjectiveCap_of_balanced
-- round 28: Chapter 7 §7.2–§7.4 (curve area functional, convex arcs, Mamikon's theorem)
#print axioms Sofa.integral_Ioc_stieltjes
#print axioms Sofa.cross_frame
#print axioms Sofa.segJ
#print axioms Sofa.segJ_self
#print axioms Sofa.segJ_comm
#print axioms Sofa.segJ_of_line
#print axioms Sofa.segJ_eq_zero_of_line_zero
#print axioms Sofa.segJ_vtxM_vtxP
#print axioms Sofa.curveJ
#print axioms Sofa.curveB
#print axioms Sofa.curveJ_eq_curveB
#print axioms Sofa.curveJ_add
#print axioms Sofa.curveJ_congr
#print axioms Sofa.curveJ_line
#print axioms Sofa.hasDerivAt_supportFn_of_edgeLength_eq_zero
#print axioms Sofa.ae_deriv_supportFn
#print axioms Sofa.lipschitzWith_supportFn
#print axioms Sofa.absolutelyContinuousOnInterval_supportFn
#print axioms Sofa.measurable_edgeMax
#print axioms Sofa.intervalIntegrable_of_bdd
#print axioms Sofa.intervalIntegrable_edgeMax_sq
#print axioms Sofa.hasDerivAt_primitive_supportFn
#print axioms Sofa.absolutelyContinuousOnInterval_primitive_supportFn
#print axioms Sofa.two_mul_curveG_eq
#print axioms Sofa.convJ
#print axioms Sofa.convJ_eq_curveG
#print axioms Sofa.two_mul_convJ_eq
#print axioms Sofa.convJ_concat
#print axioms Sofa.convB
#print axioms Sofa.convB_self
#print axioms Sofa.convB_mix_left
#print axioms Sofa.convB_mix_right
#print axioms Sofa.isQuadraticOn_convJ
#print axioms Sofa.volumeReal_eq_integral_sq_sub_sq
#print axioms Sofa.mamikonM
#print axioms Sofa.tanCurve
#print axioms Sofa.inner_tanCurve_u
#print axioms Sofa.inner_tanCurve_v
#print axioms Sofa.eq_tanCurve
#print axioms Sofa.hasDerivAt_tanCurve
#print axioms Sofa.mamikonM_eq
#print axioms Sofa.mamikonM_congr
#print axioms Sofa.mamikonM_eq'
#print axioms Sofa.mamikonM_mix_le
-- round 29: Mamikon along lines, caps (half-plane facts, |K|, Minkowski), Ch 8.3 concavity
#print axioms Sofa.ac_const
#print axioms Sofa.ac_cos_sub
#print axioms Sofa.ac_sin_sub
#print axioms Sofa.ac_inv_sin_sub
#print axioms Sofa.ac_supportFn_add
#print axioms Sofa.lineW
#print axioms Sofa.vtx2_eq_tanCurve
#print axioms Sofa.lineCurve
#print axioms Sofa.lineCurve_of_lt
#print axioms Sofa.lineCurve_self
#print axioms Sofa.sin_sub_pos_of_mem
#print axioms Sofa.ac_lineW
#print axioms Sofa.vtx2_eq_line
#print axioms Sofa.inner_vtx2_v_right
#print axioms Sofa.ac_vtx2_v_right
#print axioms Sofa.curveJ_vtx2
#print axioms Sofa.mamikonSeg
#print axioms Sofa.mamikonSeg_eq
#print axioms Sofa.continuous_segJ
#print axioms Sofa.tendsto_segJ
#print axioms Sofa.tendsto_lineCurve_left
#print axioms Sofa.tendsto_edgeMin_left
#print axioms Sofa.tendsto_convJ_left
#print axioms Sofa.tendsto_mamikonSeg_left
#print axioms Sofa.lineW_mix
#print axioms Sofa.integral_sq_mix_le
#print axioms Sofa.intervalIntegrable_sub_edgeMax_sq
#print axioms Sofa.mamikonSeg_mix_le
#print axioms Sofa.mamikonSeg_mix_le_self
#print axioms Sofa.outerCorner_eq_tanCurve
#print axioms Sofa.mamikonM_outerCorner
#print axioms Sofa.mamikonM_outerCorner_mix_le
#print axioms Sofa.hasDerivAt_frame
#print axioms Sofa.two_mul_curveJ_frame
#print axioms Sofa.curveJ_outer_sub_inner
#print axioms Sofa.mem_of_forall_inner_le_supportFn
#print axioms Sofa.IsCap.coord_one_nonneg
#print axioms Sofa.IsCap.neg_supportFn_pi_le
#print axioms Sofa.IsCap.le_supportFn_zero
#print axioms Sofa.IsCap.proj_floor_mem
#print axioms Sofa.IsCap.cornerR_mem
#print axioms Sofa.IsCap.cornerL_mem
#print axioms Sofa.IsCap.edgeMax_pi
#print axioms Sofa.IsCap.edgeMin_pi
#print axioms Sofa.IsCap.edgeMax_zero
#print axioms Sofa.IsCap.supportFn_of_mem_Icc_pi
#print axioms Sofa.IsCap.supportFn_of_mem_Icc_three_pi_div_two
#print axioms Sofa.integral_cos_sq_sub_sin_sq
#print axioms Sofa.integral_sq_sub_sq_of_eq_cos
#print axioms Sofa.volumeReal_cap
#print axioms Sofa.isCap_mix
#print axioms Sofa.interior_mix_nonempty
#print axioms Sofa.segJ_on_line
#print axioms Sofa.eq_of_inner_u_eq_two
#print axioms Sofa.inner_innerCorner_u_add
#print axioms Sofa.outerCorner_sub_innerCorner
#print axioms Sofa.vtx2_add_pi_div_two
#print axioms Sofa.ptWR
#print axioms Sofa.ptZL
#print axioms Sofa.ptWR_eq_wedgeW
#print axioms Sofa.ptZL_eq_wedgeZ
#print axioms Sofa.Qfun
#print axioms Sofa.Pfun
#print axioms Sofa.Rfun
#print axioms Sofa.Lfun
#print axioms Sofa.Sfun
#print axioms Sofa.LEq
#print axioms Sofa.Qfun_eq
#print axioms Sofa.cvecR
#print axioms Sofa.cvecL
#print axioms Sofa.vtx2_phi_eq
#print axioms Sofa.vtx2_pi_sub_phi_eq
#print axioms Sofa.Lamfun
#print axioms Sofa.segJ_top
#print axioms Sofa.Sfun_add_Pfun
#print axioms Sofa.innerCorner_mix
#print axioms Sofa.ptWR_mix
#print axioms Sofa.ptZL_mix
#print axioms Sofa.Lamfun_mix
#print axioms Sofa.Sfun_mix_le
#print axioms Sofa.Rfun_mix_le
#print axioms Sofa.Lfun_mix_le
#print axioms Sofa.LEq.mix
#print axioms Sofa.Qfun_eq_Lam
#print axioms Sofa.Qfun_concave
-- round 30: tangent caps (Green-free), B_K/D_K, Lemmas 8.1.4, 8.1.6, 8.1.7, 8.2.2
#print axioms Sofa.thick
#print axioms Sofa.supportFn_closedBall
#print axioms Sofa.isCompact_thick
#print axioms Sofa.convex_thick
#print axioms Sofa.nonempty_thick
#print axioms Sofa.interior_thick_nonempty
#print axioms Sofa.supportFn_thick
#print axioms Sofa.edgeMax_eq_of_supportFn_eq_add
#print axioms Sofa.volumeReal_eq_integral_sq_sub_sq_of_convex
#print axioms Sofa.convexHull_insert_eq_image
#print axioms Sofa.isCompact_convexHull_insert
#print axioms Sofa.supportFn_convexHull_insert
#print axioms Sofa.sin_sub_smul_u
#print axioms Sofa.supportFn_le_inner_vtx2
#print axioms Sofa.inner_vtx2_le_supportFn
#print axioms Sofa.continuous_inner_u_arg
#print axioms Sofa.continuous_inner_v_arg
#print axioms Sofa.integral_inner_u_sq_sub_inner_v_sq
#print axioms Sofa.volumeReal_convexHull_insert_vtx2
#print axioms Sofa.monotoneOn_Icc_of_rightDeriv_nonneg
#print axioms Sofa.antitoneOn_Icc_of_rightDeriv_nonpos
#print axioms Sofa.hasDerivWithinAt_inner_innerCorner
#print axioms Sofa.IsInjectiveCap.inner_innerCorner_u_le_right
#print axioms Sofa.IsInjectiveCap.inner_innerCorner_u_le_left
#print axioms Sofa.IsInjectiveCap.mem_QminusS_right
#print axioms Sofa.IsInjectiveCap.mem_QminusS_left
#print axioms Sofa.inner_ptWR_u
#print axioms Sofa.inner_ptWR_u_pi_div_two
#print axioms Sofa.ptZL_eq_smul
#print axioms Sofa.inner_ptZL_u
#print axioms Sofa.inner_ptZL_u_pi_div_two
#print axioms Sofa.IsCap.supportFn_le_right
#print axioms Sofa.IsCap.supportFn_le_left
#print axioms Sofa.IsCap.floor_mem
#print axioms Sofa.IsCap.ptWR_mem
#print axioms Sofa.IsCap.ptZL_mem
#print axioms Sofa.cos_three_pi_div_two'
#print axioms Sofa.Bset
#print axioms Sofa.Dset
#print axioms Sofa.mem_Bset
#print axioms Sofa.mem_Dset
#print axioms Sofa.Bset_subset
#print axioms Sofa.Dset_subset
#print axioms Sofa.isCompact_Bset
#print axioms Sofa.isCompact_Dset
#print axioms Sofa.convex_Bset
#print axioms Sofa.convex_Dset
#print axioms Sofa.IsCap.cornerR_mem_Bset
#print axioms Sofa.IsCap.cornerL_mem_Dset
#print axioms Sofa.IsCap.Bset_nonempty
#print axioms Sofa.IsCap.Dset_nonempty
#print axioms Sofa.IsCap.supportFn_Bset_three_pi_div_two
#print axioms Sofa.IsCap.supportFn_Dset_three_pi_div_two
#print axioms Sofa.IsCap.supportFn_add_Bset_le
#print axioms Sofa.IsCap.supportFn_add_Dset_le
#print axioms Sofa.IsInjectiveCap.supportFn_Bset_phi
#print axioms Sofa.IsInjectiveCap.supportFn_Dset_phi
#print axioms Sofa.IsInjectiveCap.leq_Bset_Dset
#print axioms Sofa.IsCap.not_mem_right_left
#print axioms Sofa.vtx2_eq_ptWR
#print axioms Sofa.vtx2_eq_ptZL
#print axioms Sofa.IsInjectiveCap.convexHull_diff_Bset_subset
#print axioms Sofa.IsInjectiveCap.convexHull_diff_Dset_subset
#print axioms Sofa.IsInjectiveCap.le_volumeReal_niche_right
#print axioms Sofa.IsInjectiveCap.le_volumeReal_niche_left
-- round 31: Lemma 8.2.3, Thm 8.2.4, the domain 𝓛 (Thm 8.1.8), A(K) ≥ 2.2 for balanced caps
#print axioms Sofa.IsInjectiveCap.edgeLength_eq_zero_left
#print axioms Sofa.IsInjectiveCap.edgeLength_eq_zero_right
#print axioms Sofa.IsInjectiveCap.hasDerivAt_innerCorner
#print axioms Sofa.IsInjectiveCap.armFp_eq_armFm
#print axioms Sofa.IsInjectiveCap.continuousOn_armFp
#print axioms Sofa.coreX
#print axioms Sofa.coreY
#print axioms Sofa.coreX'
#print axioms Sofa.coreY'
#print axioms Sofa.IsInjectiveCap.hasDerivAt_coreX
#print axioms Sofa.IsInjectiveCap.hasDerivAt_coreY
#print axioms Sofa.IsInjectiveCap.coreX'_neg
#print axioms Sofa.IsInjectiveCap.continuousOn_coreX'
#print axioms Sofa.IsInjectiveCap.continuousOn_coreY'
#print axioms Sofa.continuous_coreX
#print axioms Sofa.continuous_coreY
#print axioms Sofa.inner_deriv_u_zero
#print axioms Sofa.inner_deriv_u_pi_div_two
#print axioms Sofa.cross_eq_inner
#print axioms Sofa.IsInjectiveCap.curveJ_core
#print axioms Sofa.IsInjectiveCap.integral_core_graph
#print axioms Sofa.coreRoof
#print axioms Sofa.integrableOn_coreRoof
#print axioms Sofa.coreRoof_of_le
#print axioms Sofa.coreRoof_of_mem
#print axioms Sofa.coreRoof_of_ge
#print axioms Sofa.coreRoof_le_d
#print axioms Sofa.coreRoof_le_b
#print axioms Sofa.integral_pieces_le
#print axioms Sofa.volume_underGraph
#print axioms Sofa.integral_affine
#print axioms Sofa.inner_innerCorner_eq_coords
#print axioms Sofa.coreD
#print axioms Sofa.coreB
#print axioms Sofa.coreC
#print axioms Sofa.coreU
#print axioms Sofa.continuous_coreD
#print axioms Sofa.continuous_coreB
#print axioms Sofa.core_aux1
#print axioms Sofa.core_aux2
#print axioms Sofa.core_aux3
#print axioms Sofa.core_aux4
#print axioms Sofa.IsInjectiveCap.core_corner_right
#print axioms Sofa.IsInjectiveCap.core_corner_left
#print axioms Sofa.IsInjectiveCap.core_graph
#print axioms Sofa.IsInjectiveCap.coreC_of_mem
#print axioms Sofa.IsInjectiveCap.coreC_at
#print axioms Sofa.IsInjectiveCap.coreX_lt
#print axioms Sofa.IsInjectiveCap.core_roof
#print axioms Sofa.mem_core_region
#print axioms Sofa.IsInjectiveCap.core_region_subset
#print axioms Sofa.IsInjectiveCap.core_J_eq
#print axioms Sofa.IsInjectiveCap.le_volumeReal_niche_core
#print axioms Sofa.IsInjectiveCap.sofaArea_le_Qfun
#print axioms Sofa.IsCap.volumeReal_le_width
#print axioms Sofa.sofaArea_le_volumeReal
#print axioms Sofa.width_of_area
#print axioms Sofa.InL
#print axioms Sofa.IsInjectiveCap.inL
#print axioms Sofa.IsBalancedMaxCap.sofaArea_le_Qfun
#print axioms Sofa.IsBalancedMaxCap.inL
#print axioms Sofa.volume_le_sofaArea_of_bmc
#print axioms Sofa.IsBalancedMaxCap.two_point_two_le_sofaArea
#print axioms Sofa.intervalIntegrable_edgeMax_mul
#print axioms Sofa.integral_Ioc_supportFn_sigmaK
#print axioms Sofa.integral_Ioo_supportFn_sigmaK
#print axioms Sofa.convB_sub_convB
#print axioms Sofa.areaB_comm
#print axioms Sofa.vtxM_mix
#print axioms Sofa.segJ_mix_expand
#print axioms Sofa.volumeReal_mix_expand
#print axioms Sofa.two_mul_areaB_sub
#print axioms Sofa.convJ_mix_expand
#print axioms Sofa.convB_add_convB_sub
#print axioms Sofa.ae_deriv_supportFn_add
#print axioms Sofa.intervalIntegrable_edgeMax_add
#print axioms Sofa.intervalIntegrable_mul_edgeMax
#print axioms Sofa.intervalIntegrable_mul_edgeMax_add
#print axioms Sofa.two_mul_curveJ_innerCorner
#print axioms Sofa.cornerB
#print axioms Sofa.intervalIntegrable_cornerF
#print axioms Sofa.intervalIntegrable_cornerG
#print axioms Sofa.curveJ_innerCorner_mix_expand
#print axioms Sofa.iotaV
#print axioms Sofa.iotaU
#print axioms Sofa.cornerB_sub_two_mul_curveJ
#print axioms Sofa.dirQ
#print axioms Sofa.Qfun_le_add_dirQ
#print axioms Sofa.interior_nonempty_of_volume_ne_zero
#print axioms Sofa.InL.interior_nonempty
#print axioms Sofa.Qfun_le_of_dirQ_nonpos
#print axioms Sofa.StieltjesFunction.measure_Ioo_eq_zero_of_const
#print axioms Sofa.IsCap.edgeMax_of_mem_Ioo_pi
#print axioms Sofa.IsCap.edgeMax_of_mem_Ioo_three_pi_div_two
#print axioms Sofa.IsCap.sigmaK_Ioo_pi
#print axioms Sofa.IsCap.sigmaK_Ioo_three_pi_div_two
#print axioms Sofa.edgeMin_add_two_pi
#print axioms Sofa.edgeLength_add_two_pi
#print axioms Sofa.setIntegral_Ioc_of_null
#print axioms Sofa.setIntegral_Ioc_split
#print axioms Sofa.IsCap.setIntegral_Ioc_zero_two_pi
#print axioms Sofa.sigmaBreve
#print axioms Sofa.iotaDens
#print axioms Sofa.iotaK
#print axioms Sofa.measurable_iotaV
#print axioms Sofa.measurable_iotaU
#print axioms Sofa.measurable_iotaDens
#print axioms Sofa.setIntegral_iotaK_left
#print axioms Sofa.setIntegral_iotaK_right
#print axioms Sofa.setIntegral_sigmaBreve
#print axioms Sofa.GerverData
#print axioms Sofa.GerverData.dirQ_nonpos
#print axioms Sofa.GerverData.Qfun_le
#print axioms Sofa.sigmaK_Ioc_eq_zero_of_vtxP_mem
#print axioms Sofa.setIntegral_Ioc_of_null'
#print axioms Sofa.sigmaK_Ico_eq_zero_of_vtxM_mem
#print axioms Sofa.tendsto_sub_const_nhdsGT
#print axioms Sofa.tendsto_sub_const_nhdsLT
#print axioms Sofa.eq_vtx_of_mem_edge
#print axioms Sofa.IsInjectiveCap.mem_Bset_of_not_mem_niche
#print axioms Sofa.IsInjectiveCap.mem_Dset_of_not_mem_niche
#print axioms Sofa.IsCap.gerver_B_side
#print axioms Sofa.IsCap.gerver_D_side
#print axioms Sofa.GerverAngles
#print axioms Sofa.GerverTails
#print axioms Sofa.closure_niche_subset
#print axioms Sofa.closure_niche_subset_floor
#print axioms Sofa.mem_of_mem_Ioo
#print axioms Sofa.GerverTails.B_mem
#print axioms Sofa.GerverTails.D_mem
#print axioms Sofa.iotaV_eq
#print axioms Sofa.iotaU_eq
#print axioms Sofa.GerverTails.gerverData
#print axioms Sofa.mem_segment_of_line
#print axioms Sofa.mem_segment_of_line'
#print axioms Sofa.monotoneOn_inner_of_rightDeriv
#print axioms Sofa.GerverTails.B_x_mono
#print axioms Sofa.GerverTails.B_y_anti
#print axioms Sofa.GerverTails.D_x_mono
#print axioms Sofa.GerverTails.D_y_mono
#print axioms Sofa.GerverNiche
#print axioms Sofa.ptWR_coord_zero
#print axioms Sofa.ptWR_coord_one
#print axioms Sofa.ptZL_coord_zero
#print axioms Sofa.ptZL_coord_one
#print axioms Sofa.GerverNiche.niche_inter_right_subset
#print axioms Sofa.GerverNiche.niche_inter_left_subset
#print axioms Sofa.GerverNiche.niche_diff_subset
#print axioms Sofa.IsInjectiveCap.volumeReal_convexHull_diff_Bset
#print axioms Sofa.IsInjectiveCap.volumeReal_convexHull_diff_Dset
#print axioms Sofa.integral_pieces_eq
#print axioms Sofa.volume_floor
#print axioms Sofa.GerverNiche.coreU_nonneg
#print axioms Sofa.GerverNiche.volumeReal_niche_le
#print axioms Sofa.GerverNiche.Qfun_le_sofaArea
#print axioms Sofa.GerverNiche.sofaArea_eq_Qfun
#print axioms Sofa.restrict_Ioc_eq_of_Ioc
#print axioms Sofa.restrict_Ico_eq_of_Ioc
#print axioms Sofa.sigmaK_Ioc_toReal_eq_integral
#print axioms Sofa.sigmaBreve_Ioc
#print axioms Sofa.sigmaBreve_singleton
#print axioms Sofa.iotaK_Ioc
#print axioms Sofa.iotaK_singleton
#print axioms Sofa.intervalIntegrable_iotaV
#print axioms Sofa.intervalIntegrable_iotaU
#print axioms Sofa.v_add_pi'
#print axioms Sofa.continuousAt_vtxP_of_edgeLength_eq_zero
#print axioms Sofa.IsInjectiveCap.continuousAt_vtxP_left
#print axioms Sofa.IsInjectiveCap.continuousAt_vtxP_right
#print axioms Sofa.IsInjectiveCap.sigmaK_Ioc_eq_left
#print axioms Sofa.IsInjectiveCap.sigmaK_Ioc_eq_right
#print axioms Sofa.GerverTails.sigmaBreve_Ioc_B
#print axioms Sofa.GerverTails.sigmaBreve_Ioc_D
#print axioms Sofa.IsInjectiveCap.iotaK_Ioc_left
#print axioms Sofa.IsInjectiveCap.iotaK_Ioc_right
#print axioms Sofa.GerverODE
#print axioms Sofa.Ico_inter_Ico_eq_empty_of_le
#print axioms Sofa.Ico_inter_Ico_eq_empty_of_le'
#print axioms Sofa.Ioc_inter_Ioc_eq_empty_of_le
#print axioms Sofa.Ioc_inter_Ioc_eq_empty_of_le'
#print axioms Sofa.GerverODE.sigma_left
#print axioms Sofa.GerverODE.sigma_right
#print axioms Sofa.GerverODE.gerverData
#print axioms Sofa.IA.sinPoly
#print axioms Sofa.IA.cosPoly
#print axioms Sofa.IA.hasDerivAt_sinPoly
#print axioms Sofa.IA.cosPoly_succ
#print axioms Sofa.IA.hasDerivAt_cosPoly
#print axioms Sofa.IA.sinPoly_zero
#print axioms Sofa.IA.cosPoly_succ_zero
#print axioms Sofa.IA.nonpos_of_deriv_nonpos
#print axioms Sofa.IA.taylor_alt
#print axioms Sofa.IA.even_neg_one_pow
#print axioms Sofa.IA.odd_neg_one_pow
#print axioms Sofa.IA.sin_le_sinPoly
#print axioms Sofa.IA.sinPoly_le_sin
#print axioms Sofa.IA.cos_le_cosPoly
#print axioms Sofa.IA.cosPoly_le_cos
#print axioms Sofa.IA.S
#print axioms Sofa.IA.S_pos'
#print axioms Sofa.IA.S_pos
#print axioms Sofa.IA.fdivS
#print axioms Sofa.IA.cdivS
#print axioms Sofa.IA.fdivS_le
#print axioms Sofa.IA.le_cdivS
#print axioms Sofa.IA.qdn
#print axioms Sofa.IA.qup
#print axioms Sofa.IA.qdn_le
#print axioms Sofa.IA.le_qup
#print axioms Sofa.IA.Iv
#print axioms Sofa.IA.Iv.Mem
#print axioms Sofa.IA.Iv.add
#print axioms Sofa.IA.Iv.neg
#print axioms Sofa.IA.Iv.sub
#print axioms Sofa.IA.Iv.mul
#print axioms Sofa.IA.Iv.const
#print axioms Sofa.IA.Iv.mem_add
#print axioms Sofa.IA.Iv.mem_neg
#print axioms Sofa.IA.Iv.mem_sub
#print axioms Sofa.IA.Iv.mem_const
#print axioms Sofa.IA.min_le_mul_of_mem
#print axioms Sofa.IA.mul_le_max_of_mem
#print axioms Sofa.IA.mul_mem_corners
#print axioms Sofa.IA.Iv.mem_mul
#print axioms Sofa.IA.IE
#print axioms Sofa.IA.IE.eval
#print axioms Sofa.IA.IE.ieval
#print axioms Sofa.IA.IE.mem_ieval
#print axioms Sofa.IA.tX
#print axioms Sofa.IA.tY
#print axioms Sofa.IA.sin6E
#print axioms Sofa.IA.sin7E
#print axioms Sofa.IA.cos6E
#print axioms Sofa.IA.cos7E
#print axioms Sofa.IA.sin6E_eval
#print axioms Sofa.IA.sin7E_eval
#print axioms Sofa.IA.cos6E_eval
#print axioms Sofa.IA.cos7E_eval
#print axioms Sofa.IA.mem_ieval_point
#print axioms Sofa.IA.sinLB
#print axioms Sofa.IA.sinUB
#print axioms Sofa.IA.cosLB
#print axioms Sofa.IA.cosUB
#print axioms Sofa.IA.sinLB_le
#print axioms Sofa.IA.le_sinUB
#print axioms Sofa.IA.cosLB_le
#print axioms Sofa.IA.le_cosUB
#print axioms Sofa.IA.Iv.sin
#print axioms Sofa.IA.Iv.cos
#print axioms Sofa.IA.Iv.mem_sin
#print axioms Sofa.IA.Iv.mem_cos
#print axioms Sofa.IA.Iv.nonzero
#print axioms Sofa.IA.Iv.ne_zero_of_nonzero
#print axioms Sofa.IA.Iv.mag
#print axioms Sofa.IA.Iv.abs_le_mag
#print axioms Sofa.IA.Iv.mem_one
#print axioms Sofa.IA.Iv.mem_line
#print axioms Sofa.IA.IE.evalD
#print axioms Sofa.IA.IE.hasDerivAt_eval
#print axioms Sofa.IA.IE.evalD_lin
#print axioms Sofa.IA.IE.diff
#print axioms Sofa.IA.IE.eval_diff
#print axioms Sofa.GC.Spec
#print axioms Sofa.GC.eq1
#print axioms Sofa.GC.eq2
#print axioms Sofa.GC.eq3
#print axioms Sofa.GC.eq4
#print axioms Sofa.GC.spec_iff
#print axioms Sofa.GC.vφ
#print axioms Sofa.GC.vθ
#print axioms Sofa.GC.vπ
#print axioms Sofa.GC.sφ
#print axioms Sofa.GC.cφ
#print axioms Sofa.GC.sθ
#print axioms Sofa.GC.cθ
#print axioms Sofa.GC.k
#print axioms Sofa.GC.dE
#print axioms Sofa.GC.N1E
#print axioms Sofa.GC.denE
#print axioms Sofa.GC.kkE
#print axioms Sofa.GC.c0E
#print axioms Sofa.GC.QE
#print axioms Sofa.GC.RE
#print axioms Sofa.GC.envOf
#print axioms Sofa.GC.eq1_sub_eq3
#print axioms Sofa.GC.eq4_eq
#print axioms Sofa.GC.QE_eval
#print axioms Sofa.GC.RE_eval
#print axioms Sofa.GC.QE_RE_eq_zero
#print axioms Sofa.GC.piIv
#print axioms Sofa.GC.mem_piIv
#print axioms Sofa.GC.boxOf
#print axioms Sofa.GC.mem_boxOf
#print axioms Sofa.GC.leaf
#print axioms Sofa.GC.check
#print axioms Sofa.GC.leaf_sound
#print axioms Sofa.GC.check_sound
#print axioms Sofa.GC.cφ₀
#print axioms Sofa.GC.cθ₀
#print axioms Sofa.GC.rad
#print axioms Sofa.GC.target
#print axioms Sofa.GC.top
#print axioms Sofa.GC.top_ge
#print axioms Sofa.GC.check_succ_of
#print axioms Sofa.GC.check_top
#print axioms Sofa.GC.Spec_mem_target
#print axioms Sofa.GC.dφ
#print axioms Sofa.GC.dθ
#print axioms Sofa.GC.lineEnv
#print axioms Sofa.GC.hasDerivAt_lineEnv
#print axioms Sofa.GC.lineEnv_one
#print axioms Sofa.GC.lineEnv_zero
#print axioms Sofa.GC.IE_mvt
#print axioms Sofa.GC.boxSet
#print axioms Sofa.GC.mem_boxSet
#print axioms Sofa.GC.G1E
#print axioms Sofa.GC.G2E
#print axioms Sofa.GC.Tmap
#print axioms Sofa.GC.contrOK
#print axioms Sofa.GC.contrOK_target
#print axioms Sofa.GC.half_of_le
#print axioms Sofa.GC.abs_sub_le_add_abs
#print axioms Sofa.GC.abs_lin_le
#print axioms Sofa.GC.lip_of_contrOK
#print axioms Sofa.GC.fixed_of_zero
#print axioms Sofa.GC.zero_of_fixed
#print axioms Sofa.GC.fixed_unique
#print axioms Sofa.GC.tbox
#print axioms Sofa.GC.mapOK
#print axioms Sofa.GC.mapOK_true
#print axioms Sofa.GC.tbox_sub
#print axioms Sofa.GC.le_half_of_two_mul_le
#print axioms Sofa.GC.ctr
#print axioms Sofa.GC.ctr_mem
#print axioms Sofa.GC.mem_iff_abs
#print axioms Sofa.GC.maps_tbox
#print axioms Sofa.GC.isClosed_boxSet
#print axioms Sofa.GC.exists_fixed
#print axioms Sofa.GC.posOK
#print axioms Sofa.GC.posOK_true
#print axioms Sofa.GC.pos_of_lo
#print axioms Sofa.GC.pos_on_target
#print axioms Sofa.GC.denE_eval
#print axioms Sofa.GC.target_angles
#print axioms Sofa.GC.spec_of_zero
#print axioms Sofa.GC.spec_existsUnique
#print axioms Sofa.GC.Spec_mem_tbox
#print axioms Sofa.GC.Spec_angles
#print axioms Sofa.GC.gerver_spec
#print axioms Sofa.GC.gerver_mem_tbox
#print axioms Sofa.GC.gerver_angles
-- Gerver's sofa: the path, closed forms, connectedness; it is a moving sofa (round 38)
-- GerverPath.lean
#print axioms Sofa.GP.φ_mem
#print axioms Sofa.GP.θ_mem
#print axioms Sofa.GP.A_eq
#print axioms Sofa.GP.B_eq
#print axioms Sofa.GP.aLo
#print axioms Sofa.GP.aHi
#print axioms Sofa.GP.bLo
#print axioms Sofa.GP.bHi
#print axioms Sofa.GP.tb
#print axioms Sofa.GP.abOK
#print axioms Sofa.GP.abOK_true
#print axioms Sofa.GP.tb_mem
#print axioms Sofa.GP.lo_le
#print axioms Sofa.GP.le_hi
#print axioms Sofa.GP.A_mem
#print axioms Sofa.GP.B_mem
#print axioms Sofa.GP.bounds
#print axioms Sofa.GP.r_def
#print axioms Sofa.GP.measurable_r
#print axioms Sofa.GP.r_nonneg_le
#print axioms Sofa.GP.intervalIntegrable_r
#print axioms Sofa.GP.intervalIntegrable_r_mul
#print axioms Sofa.GP.y_eq
#print axioms Sofa.GP.x_eq
#print axioms Sofa.GP.continuous_y
#print axioms Sofa.GP.continuous_x
#print axioms Sofa.GP.x_end
#print axioms Sofa.GP.y_end
#print axioms Sofa.GP.p₁
#print axioms Sofa.GP.p₂
#print axioms Sofa.GP.p_coord_zero
#print axioms Sofa.GP.p_coord_one
#print axioms Sofa.GP.p_eq
#print axioms Sofa.GP.continuous_p₁
#print axioms Sofa.GP.continuous_p₂
#print axioms Sofa.GP.continuous_p
#print axioms Sofa.GP.integral_quad_mul_sin
#print axioms Sofa.GP.r_piece₂
#print axioms Sofa.GP.r_piece₃
#print axioms Sofa.GP.r_piece₄
#print axioms Sofa.GP.y_zero
#print axioms Sofa.GP.p_zero
#print axioms Sofa.GP.ang
#print axioms Sofa.GP.continuous_ang
#print axioms Sofa.GP.ang_mem
#print axioms Sofa.GP.gmotion
#print axioms Sofa.GP.gmotion_apply
#print axioms Sofa.GP.continuous_gmotion
#print axioms Sofa.GP.gmotion_zero
#print axioms Sofa.GP.isClosed_rotateTranslate_image
#print axioms Sofa.GP.isClosed_horizontalHallway
#print axioms Sofa.GP.isClosed_verticalHallway
#print axioms Sofa.GP.isClosed_gerversSofa
#print axioms Sofa.GP.isMovingSofa_gerversSofa_of_isConnected
-- GerverClosed.lean
#print axioms Sofa.GP.Fs
#print axioms Sofa.GP.Fc
#print axioms Sofa.GP.integral_quad_sin
#print axioms Sofa.GP.integral_quad_cos
#print axioms Sofa.GP.brk
#print axioms Sofa.GP.ra
#print axioms Sofa.GP.rb
#print axioms Sofa.GP.rc
#print axioms Sofa.GP.brk_mono
#print axioms Sofa.GP.r_eq_quad
#print axioms Sofa.GP.integral_piece_sin
#print axioms Sofa.GP.integral_piece_cos
#print axioms Sofa.GP.SY
#print axioms Sofa.GP.SX
#print axioms Sofa.GP.tailY
#print axioms Sofa.GP.tailX
#print axioms Sofa.GP.intervalIntegrable_r_sin
#print axioms Sofa.GP.intervalIntegrable_r_cos
#print axioms Sofa.GP.integral_tail_sin
#print axioms Sofa.GP.integral_tail_cos
#print axioms Sofa.GP.yC
#print axioms Sofa.GP.xC
#print axioms Sofa.GP.y_eq_yC
#print axioms Sofa.GP.x_eq_xC
#print axioms Sofa.GP.x0C
#print axioms Sofa.GP.x_zero_eq
#print axioms Sofa.GP.p₁C
#print axioms Sofa.GP.p₂C
#print axioms Sofa.GP.brk_reflect
#print axioms Sofa.GP.p₁_eq_closed
#print axioms Sofa.GP.p₂_eq_closed
-- GerverConn.lean
#print axioms Sofa.GP.q157
#print axioms Sofa.GP.sinW
#print axioms Sofa.GP.cosW
#print axioms Sofa.GP.mem_sinW
#print axioms Sofa.GP.mem_cosW
#print axioms Sofa.GP.envA
#print axioms Sofa.GP.boxA
#print axioms Sofa.GP.mem_boxA
#print axioms Sofa.GP.eα
#print axioms Sofa.GP.esα
#print axioms Sofa.GP.ecα
#print axioms Sofa.GP.eφ
#print axioms Sofa.GP.eθ
#print axioms Sofa.GP.eπ
#print axioms Sofa.GP.esφ
#print axioms Sofa.GP.ecφ
#print axioms Sofa.GP.esθ
#print axioms Sofa.GP.ecθ
#print axioms Sofa.GP.eA
#print axioms Sofa.GP.eB
#print axioms Sofa.GP.FsE
#print axioms Sofa.GP.FcE
#print axioms Sofa.GP.FsE_eval
#print axioms Sofa.GP.FcE_eval
#print axioms Sofa.GP.eHφ
#print axioms Sofa.GP.eHθ
#print axioms Sofa.GP.raE
#print axioms Sofa.GP.rbE
#print axioms Sofa.GP.rcE
#print axioms Sofa.GP.brkE
#print axioms Sofa.GP.sbrkE
#print axioms Sofa.GP.cbrkE
#print axioms Sofa.GP.raE_eval
#print axioms Sofa.GP.rbE_eval
#print axioms Sofa.GP.rcE_eval
#print axioms Sofa.GP.brkE_eval
#print axioms Sofa.GP.SYE
#print axioms Sofa.GP.SXE
#print axioms Sofa.GP.SYE_eval
#print axioms Sofa.GP.SXE_eval
#print axioms Sofa.GP.tailYE
#print axioms Sofa.GP.tailXE
#print axioms Sofa.GP.tailYE_eval
#print axioms Sofa.GP.tailXE_eval
#print axioms Sofa.GP.yCE
#print axioms Sofa.GP.xCE
#print axioms Sofa.GP.yCE_eval
#print axioms Sofa.GP.xCE_eval
#print axioms Sofa.GP.x0E
#print axioms Sofa.GP.x0E_eval
#print axioms Sofa.GP.eβ
#print axioms Sofa.GP.eβ_eval
#print axioms Sofa.GP.p1E
#print axioms Sofa.GP.p2E
#print axioms Sofa.GP.p1E_eval
#print axioms Sofa.GP.p2E_eval
#print axioms Sofa.GP.brkLo
#print axioms Sofa.GP.brkHi
#print axioms Sofa.GP.half_pi_lo
#print axioms Sofa.GP.half_pi_hi
#print axioms Sofa.GP.brk_bounds
#print axioms Sofa.GP.pieceOK
#print axioms Sofa.GP.pieceOK_sound
#print axioms Sofa.GP.chkA
#print axioms Sofa.GP.chkA_sound
#print axioms Sofa.GP.exists_piece
#print axioms Sofa.GP.topA
#print axioms Sofa.GP.mem_top
#print axioms Sofa.GP.of_chkA
#print axioms Sofa.GP.envA_sin
#print axioms Sofa.GP.envA_cos
#print axioms Sofa.GP.F1E
#print axioms Sofa.GP.ck_F1
#print axioms Sofa.GP.Q1
#print axioms Sofa.GP.F2E
#print axioms Sofa.GP.ck_F2
#print axioms Sofa.GP.F3E
#print axioms Sofa.GP.ck_F3
#print axioms Sofa.GP.x0OK
#print axioms Sofa.GP.x0OK_true
#print axioms Sofa.GP.x0_bounds
#print axioms Sofa.GP.y_le_one
#print axioms Sofa.GP.x_le
#print axioms Sofa.GP.Q2L
#print axioms Sofa.GP.Q2R
#print axioms Sofa.GP.aRE
#print axioms Sofa.GP.bRE
#print axioms Sofa.GP.aLE
#print axioms Sofa.GP.bLE
#print axioms Sofa.GP.ck_aR
#print axioms Sofa.GP.ck_bR
#print axioms Sofa.GP.ck_aL
#print axioms Sofa.GP.ck_bL
#print axioms Sofa.GP.ca
#print axioms Sofa.GP.cb
#print axioms Sofa.GP.ca_pt
#print axioms Sofa.GP.cb_pt
#print axioms Sofa.GP.ca_eq
#print axioms Sofa.GP.cb_eq
#print axioms Sofa.GP.mem_image_rotateTranslate
#print axioms Sofa.GP.frame_coords
#print axioms Sofa.GP.mem_L_iff
#print axioms Sofa.GP.p_half
#print axioms Sofa.GP.mem_H0_iff
#print axioms Sofa.GP.mem_H1_iff
#print axioms Sofa.GP.Cvx
#print axioms Sofa.GP.mem_Cvx
#print axioms Sofa.GP.mem_gerversSofa_iff
#print axioms Sofa.GP.combo_coord
#print axioms Sofa.GP.convex_Cvx
#print axioms Sofa.GP.convex_coord_ge
#print axioms Sofa.GP.convex_coord_le
#print axioms Sofa.GP.mem_of_high
#print axioms Sofa.GP.mem_of_left
#print axioms Sofa.GP.mem_of_right
#print axioms Sofa.GP.up_mem
#print axioms Sofa.GP.right_mem_Cvx
#print axioms Sofa.GP.left_mem_Cvx
#print axioms Sofa.GP.mid_mem_Cvx
#print axioms Sofa.GP.isConnected_gerversSofa
#print axioms Sofa.GP.isMovingSofa_gerversSofa'
-- Gerver's sofa is a monotone sofa (round 39)
-- GerverMono.lean
#print axioms Sofa.GP.r_zero
#print axioms Sofa.GP.integral_r_mul_zero
#print axioms Sofa.GP.x_of_ge
#print axioms Sofa.GP.y_of_ge
#print axioms Sofa.GP.x_sub
#print axioms Sofa.GP.y_sub
#print axioms Sofa.GP.r_sin_nonneg
#print axioms Sofa.GP.r_cos_nonneg
#print axioms Sofa.GP.x_mono
#print axioms Sofa.GP.y_anti
#print axioms Sofa.GP.x_range
#print axioms Sofa.GP.y_range
#print axioms Sofa.GP.one_sub_y_le
#print axioms Sofa.GP.p₁_uniform
#print axioms Sofa.GP.p₂_uniform
#print axioms Sofa.GP.conv_ineq
#print axioms Sofa.GP.one_sub_cos_le_sin
#print axioms Sofa.GP.one_sub_sin_le_cos
#print axioms Sofa.GP.ptA
#print axioms Sofa.GP.ptC
#print axioms Sofa.GP.ca_ptA
#print axioms Sofa.GP.cb_ptC
#print axioms Sofa.GP.reflect_mem
#print axioms Sofa.GP.ca_ptA_le
#print axioms Sofa.GP.cb_ptC_le
#print axioms Sofa.GP.cb_ptA_le
#print axioms Sofa.GP.ca_ptC_le
#print axioms Sofa.GP.yAE
#print axioms Sofa.GP.xAE
#print axioms Sofa.GP.yAE_eval
#print axioms Sofa.GP.xAE_eval
#print axioms Sofa.GP.yHighE
#print axioms Sofa.GP.xFarE
#print axioms Sofa.GP.ck_yHigh
#print axioms Sofa.GP.ck_xFar
#print axioms Sofa.GP.high_or_far
#print axioms Sofa.GP.ptA_mem_Cvx
#print axioms Sofa.GP.ptC_mem_Cvx
#print axioms Sofa.GP.ptA_mem
#print axioms Sofa.GP.ptC_mem
#print axioms Sofa.GP.isCompact_gerversSofa
#print axioms Sofa.GP.gerversSofa_nonempty
#print axioms Sofa.GP.supportFn_gerver
#print axioms Sofa.GP.supportFn_gerver'
#print axioms Sofa.GP.suppHallway_gerver
#print axioms Sofa.GP.Imono_gerver
#print axioms Sofa.GP.rot_zero_vec
#print axioms Sofa.GP.isSofaWithAngle_gerver
#print axioms Sofa.GP.stdPos_gerver
#print axioms Sofa.GP.isMonotoneSofa_gerversSofa
-- Main: (I3″) restated for the cap of the upstream set (round 39)
#print axioms Sofa.GerverNicheFacts.toGerverNiche
#print axioms Sofa.niche_Ccap_gerversSofa_subset
#print axioms Sofa.ofReal_sofaArea_Ccap_gerversSofa
-- the cap of Gerver's sofa, `|K| ≥ 2.2`, Romik's ODEs, the ends of the tails (round 39)
-- GerverCap.lean
#print axioms Sofa.GP.Kg
#print axioms Sofa.GP.isCap_Kg
#print axioms Sofa.GP.gerversSofa_subset_Kg
#print axioms Sofa.GP.supportFn_Kg_eq
#print axioms Sofa.GP.supportFn_Kg
#print axioms Sofa.GP.supportFn_Kg'
#print axioms Sofa.GP.innerCorner_Kg
#print axioms Sofa.GP.mem_para_iff
#print axioms Sofa.GP.ca_zero
#print axioms Sofa.GP.cb_pi_div_two
#print axioms Sofa.GP.mem_Cvx_iff_para
#print axioms Sofa.GP.Ccap_gerver
#print axioms Sofa.GP.trL
#print axioms Sofa.GP.trR
#print axioms Sofa.GP.ptC_zero
#print axioms Sofa.GP.ptC_pi_div_two
#print axioms Sofa.GP.ptA_zero
#print axioms Sofa.GP.ptA_pi_div_two
#print axioms Sofa.GP.pt_combo
#print axioms Sofa.GP.pt_mem_Cvx_of_trap
#print axioms Sofa.GP.measurableSet_trap
#print axioms Sofa.GP.volume_trap_le
#print axioms Sofa.GP.volume_trap
#print axioms Sofa.GP.area_Kg
-- GerverRomik.lean
#print axioms Sofa.GP.continuousAt_r
#print axioms Sofa.GP.continuousAt_r_top
#print axioms Sofa.GP.good
#print axioms Sofa.GP.isOpen_good
#print axioms Sofa.GP.mem_good
#print axioms Sofa.GP.good_reflect
#print axioms Sofa.GP.continuousAt_r_of_good
#print axioms Sofa.GP.good_of_mem
#print axioms Sofa.GP.hasDerivAt_x
#print axioms Sofa.GP.hasDerivAt_y
#print axioms Sofa.GP.hasDerivAt_xr
#print axioms Sofa.GP.hasDerivAt_yr
#print axioms Sofa.GP.dp₁
#print axioms Sofa.GP.dp₂
#print axioms Sofa.GP.p₁_eq_fun
#print axioms Sofa.GP.p₂_eq_fun
#print axioms Sofa.GP.hasDerivAt_p₁
#print axioms Sofa.GP.hasDerivAt_p₂
#print axioms Sofa.GP.hasDerivAt_dp₁
#print axioms Sofa.GP.hasDerivAt_dp₂
#print axioms Sofa.GP.edgeMax_Kg
#print axioms Sofa.GP.edgeMax_Kg'
#print axioms Sofa.GP.vtxP_Kg
#print axioms Sofa.GP.vtxP_Kg_add
#print axioms Sofa.GP.hasDerivAt_ptA
#print axioms Sofa.GP.hasDerivAt_ptC
#print axioms Sofa.GP.hasDerivAt_vtxP
#print axioms Sofa.GP.hasDerivAt_vtxP_add
#print axioms Sofa.GP.deriv_vtxP
#print axioms Sofa.GP.deriv_vtxP_add
#print axioms Sofa.GP.hasDerivAt_innerCorner
#print axioms Sofa.GP.deriv_innerCorner
#print axioms Sofa.GP.Bg
#print axioms Sofa.GP.Dg
#print axioms Sofa.GP.hasDerivAt_Bg
#print axioms Sofa.GP.hasDerivAt_Dg
#print axioms Sofa.GP.derivWithin_Bg
#print axioms Sofa.GP.derivWithin_Dg
#print axioms Sofa.GP.continuous_dp₁
#print axioms Sofa.GP.continuous_dp₂
#print axioms Sofa.GP.continuous_Bg
#print axioms Sofa.GP.continuous_Dg
#print axioms Sofa.GP.Bg_wall
#print axioms Sofa.GP.Dg_wall
#print axioms Sofa.GP.p₂_sub_dp₁
#print axioms Sofa.GP.p₁_add_dp₂
#print axioms Sofa.GP.F_piece2
#print axioms Sofa.GP.F_piece3
#print axioms Sofa.GP.F_piece1
#print axioms Sofa.GP.F_eq_r
#print axioms Sofa.GP.F_eq_two_r
#print axioms Sofa.GP.inner_smul_u_u
#print axioms Sofa.GP.inner_smul_v_v
#print axioms Sofa.GP.r_of_le_φ
#print axioms Sofa.GP.gerverODE_Kg
-- GerverEnds.lean
#print axioms Sofa.GP.vec_eq_of_proj
#print axioms Sofa.GP.x_θ_eq
#print axioms Sofa.GP.y_θ_eq
#print axioms Sofa.GP.x_φ_eq
#print axioms Sofa.GP.y_φ_eq
#print axioms Sofa.GP.Bg_start
#print axioms Sofa.GP.Dg_end
-- GerverTailDeriv.lean
#print axioms Sofa.GP.continuousWithinAt_r_Iic
#print axioms Sofa.GP.rR
#print axioms Sofa.GP.tendsto_r_right
#print axioms Sofa.GP.rR_lt_one
#print axioms Sofa.GP.Bg_deriv
#print axioms Sofa.GP.Dg_deriv
-- GerverInj.lean
#print axioms Sofa.GP.brkSet
#print axioms Sofa.GP.brkSet_countable
#print axioms Sofa.GP.mem_brkSet_reflect
#print axioms Sofa.GP.continuousAt_r_of_not_mem
#print axioms Sofa.GP.continuousAt_r_reflect
#print axioms Sofa.GP.p₁_sub
#print axioms Sofa.GP.p₂_sub
#print axioms Sofa.GP.hasDerivAt_p₁'
#print axioms Sofa.GP.hasDerivAt_p₂'
#print axioms Sofa.GP.intervalIntegrable_r_reflect
#print axioms Sofa.GP.p₁_bound
#print axioms Sofa.GP.p₂_bound
#print axioms Sofa.GP.dp₁_lip
#print axioms Sofa.GP.dp₂_lip
#print axioms Sofa.GP.dp₁_zero
#print axioms Sofa.GP.dp₂_half
#print axioms Sofa.GP.edgeMax_Kg_of
#print axioms Sofa.GP.edgeMin_Kg_of
#print axioms Sofa.GP.edgeMax_Kg_add_of
#print axioms Sofa.GP.supportFn_Kg_neg
#print axioms Sofa.GP.supportFn_Kg_pi
#print axioms Sofa.GP.edgeMin_Kg_zero
#print axioms Sofa.GP.edgeMax_Kg_pi
#print axioms Sofa.GP.edgeMax_Kg_add_of'
#print axioms Sofa.GP.supportFn_Kg_le
#print axioms Sofa.GP.supportFn_Kg_le'
#print axioms Sofa.GP.integral_supportFn_Kg_le
#print axioms Sofa.GP.arcFn_Kg_sub
#print axioms Sofa.GP.arcFn_Kg_lip_left
#print axioms Sofa.GP.arcFn_Kg_lip_right
#print axioms Sofa.GP.edgeLength_Kg_zero
#print axioms Sofa.GP.sigmaK_Kg_ac_left
#print axioms Sofa.GP.sigmaK_Kg_ac_right
#print axioms Sofa.GP.armFm_Kg
#print axioms Sofa.GP.armGp_Kg
#print axioms Sofa.GP.armFp_Kg
#print axioms Sofa.GP.x_piece0
#print axioms Sofa.GP.y_piece0
#print axioms Sofa.GP.r_pos_mid
#print axioms Sofa.GP.F_pos
#print axioms Sofa.GP.isInjectiveCap_Kg
-- GerverArch.lean
#print axioms Sofa.monotoneOn_of_hasDerivAt_nonneg_off_countable
#print axioms Sofa.antitoneOn_of_hasDerivAt_nonpos_off_countable
#print axioms Sofa.min_le_of_hasDerivAt_mul
#print axioms Sofa.GP.Fr
#print axioms Sofa.GP.Gr
#print axioms Sofa.GP.Gr_eq
#print axioms Sofa.GP.xKg
#print axioms Sofa.GP.innerCorner_Kg_eq
#print axioms Sofa.GP.continuous_xKg
#print axioms Sofa.GP.continuous_Fr
#print axioms Sofa.GP.continuous_Gr
#print axioms Sofa.GP.hasDerivAt_xKg
#print axioms Sofa.GP.ca_xKg_self
#print axioms Sofa.GP.cb_xKg_self
#print axioms Sofa.GP.cb_Dg_self
#print axioms Sofa.GP.ca_Dg_self
#print axioms Sofa.GP.ca_Bg_self
#print axioms Sofa.GP.cb_Bg_self
#print axioms Sofa.GP.hasDerivAt_ca_comp
#print axioms Sofa.GP.hasDerivAt_cb_comp
#print axioms Sofa.inner_u_v_eq_neg_sin
#print axioms Sofa.GP.hasDerivAt_ca_xKg
#print axioms Sofa.GP.hasDerivAt_cb_xKg
#print axioms Sofa.GP.hasDerivAt_ca_Dg
#print axioms Sofa.GP.hasDerivAt_cb_Dg
#print axioms Sofa.GP.refl
#print axioms Sofa.GP.p₂_reflect
#print axioms Sofa.GP.p₁_reflect
#print axioms Sofa.GP.dp₂_reflect
#print axioms Sofa.GP.ca_refl
#print axioms Sofa.GP.cb_refl
#print axioms Sofa.GP.refl_coord_one
#print axioms Sofa.GP.refl_coord_zero
#print axioms Sofa.GP.refl_Dg
#print axioms Sofa.GP.refl_xKg
#print axioms Sofa.GP.Fr_lin
#print axioms Sofa.GP.Fr_quad
#print axioms Sofa.GP.Fr_quad_ge
#print axioms Sofa.GP.monotoneOn_Fr
#print axioms Sofa.GP.core_reflect
#print axioms Sofa.GP.φ_le_half_sub
#print axioms Sofa.GP.Fr_ge_A
#print axioms Sofa.GP.antitoneOn_Gr
#print axioms Sofa.GP.Gr_ge_A
#print axioms Sofa.GP.A_pos
#print axioms Sofa.GP.sR
#print axioms Sofa.GP.sR_facts
#print axioms Sofa.GP.θ_lt_sR
#print axioms Sofa.GP.r_le_one
#print axioms Sofa.GP.one_le_r
#print axioms Sofa.GP.continuous_ca_comp
#print axioms Sofa.GP.continuous_cb_comp
#print axioms Sofa.GP.intervalIntegrable_one_sub_r_mul
#print axioms Sofa.GP.cb_Dg_nonneg_low
#print axioms Sofa.GP.cb_Dg_ge_theta
#print axioms Sofa.GP.ca_add_cb_Dg_ge_theta
#print axioms Sofa.GP.Dg_theta
#print axioms Sofa.GP.Bg_start'
#print axioms Sofa.GP.xKg_phi_refl
#print axioms Sofa.GP.ca_xKg
#print axioms Sofa.GP.cb_xKg
#print axioms Sofa.GP.continuous_ca_const
#print axioms Sofa.GP.continuous_cb_const
#print axioms Sofa.GP.hasDerivAt_ca_pt
#print axioms Sofa.GP.hasDerivAt_cb_pt
#print axioms Sofa.GP.p₁_top
#print axioms Sofa.GP.dp₁_top
#print axioms Sofa.GP.p₂_top
#print axioms Sofa.GP.dp₂_top
#print axioms Sofa.GP.p₁_JL
#print axioms Sofa.GP.p₂_JL
#print axioms Sofa.GP.JL_bounds
#print axioms Sofa.GP.ca_JL_nonneg_top
#print axioms Sofa.GP.ca_add_cb_JL_top
#print axioms Sofa.GP.cb_JL_sturm
#print axioms Sofa.GP.cb_JL_nonneg
#print axioms Sofa.GP.ca_JR_nonneg
#print axioms Sofa.GP.cb_JR_nonneg
#print axioms Sofa.GP.cb_Dg_nonneg
#print axioms Sofa.GP.Dg_not_mem
#print axioms Sofa.GP.ca_xKg_nonneg
#print axioms Sofa.GP.cb_xKg_nonneg
#print axioms Sofa.GP.xKg_not_mem
#print axioms Sofa.GP.Bg_not_mem
#print axioms Sofa.GP.Dg_zero_coord0
#print axioms Sofa.GP.Dg_zero_coord1
#print axioms Sofa.GP.cb_Dg_zero_nonneg
#print axioms Sofa.GP.ca_Bg_half_nonneg
-- GerverNiche.lean
#print axioms Sofa.GP.mem_niche_Kg
#print axioms Sofa.GP.not_mem_niche_of
#print axioms Sofa.GP.Bg_not_mem_niche
#print axioms Sofa.GP.Dg_not_mem_niche
#print axioms Sofa.GP.hasDerivAt_coord
#print axioms Sofa.GP.continuous_coord
#print axioms Sofa.GP.Dg_coord1_nonneg
#print axioms Sofa.GP.Bg_coord1_nonneg
#print axioms Sofa.GP.xKg_coord1_pos
#print axioms Sofa.GP.inner_add_u_v_u
#print axioms Sofa.GP.inner_add_u_v_v
#print axioms Sofa.GP.ca_sub_smul
#print axioms Sofa.GP.cb_sub_smul
#print axioms Sofa.GP.norm_u_add_v_le
#print axioms Sofa.GP.norm_u_zero
#print axioms Sofa.GP.innerCorner_mem_closure
#print axioms Sofa.GP.Dg_mem_closure
#print axioms Sofa.GP.Bg_mem_closure
#print axioms Sofa.GP.Bg_half_coord1
#print axioms Sofa.GP.niche_below
-- the upstream existence-and-uniqueness theorem, now proved (round 37)
#print axioms MovingSofa.GerversSofa.ABφθSpec.existsUnique
#print axioms MovingSofa.gerversSofa
-- the conditional main theorem (for an arbitrary target set `G`): must be axiom-clean
#print axioms Sofa.Interfaces.sofaConstant_le
-- the main theorem (Baek's Theorem 1.1.1): axiom-clean since round 41
#print axioms Sofa.sofaConstant_le_volume_gerversSofa
#print axioms Sofa.sofaConstant_eq_volume_gerversSofa'
-- the four upstream statements of formal-conjectures proved here (`SofaSubmission/Solution.lean`)
#print axioms MovingSofa.GerversSofa.ABφθSpec.existsUnique
#print axioms MovingSofa.isMovingSofa_gerversSofa
#print axioms MovingSofa.sofaConstant_eq
#print axioms MovingSofa.sofaConstant_eq_volume_gerversSofa
