/-
# scripts/AuditAll.lean — axiom audit of every constant of the development

`Sofa/Check.lean` prints `#print axioms` for 1473 named results.  This script checks every constant
declared in the modules `Sofa.*` and `SofaSubmission.*` that `Sofa` and `SofaSubmission.Solution`
import (so not `SofaSubmission.Challenge`, which keeps the upstream `sorry`s), except the audit
file `Sofa.Check`; auxiliary declarations generated by Lean are included.  It reports the number
of theorems and of other constants, the union of the axioms they use, and the constants that use
an axiom other than `propext`, `Classical.choice` and `Quot.sound`.

Run from the repository root:  `lake env lean scripts/AuditAll.lean`
Expected output (commit 838baca; the order of the three axioms may differ):
  theorems: 3773, other constants: 688; union of axioms: [Quot.sound, Classical.choice, propext];
  constants with other axioms: 0 []
-/
import Sofa
import SofaSubmission.Solution
open Lean Elab Command

/-- `collectAxioms` for every declaration of the modules `Sofa.*` and `SofaSubmission.*`
(excluding `Sofa.Check`), aggregated. -/
elab "#audit_all_sofa" : command => do
  let env ← getEnv
  let mods := env.header.moduleNames
  let std : NameSet := NameSet.empty |>.insert ``propext |>.insert ``Classical.choice |>.insert ``Quot.sound
  let mut nThm : Nat := 0
  let mut nOther : Nat := 0
  let mut union : NameSet := {}
  let mut bad : Array (Name × Array Name) := #[]
  for (n, ci) in env.constants.map₁.toList do
    match env.getModuleIdxFor? n with
    | none => continue
    | some idx =>
      let m := mods[idx.toNat]!
      unless (m.getRoot == `Sofa || m.getRoot == `SofaSubmission) do continue
      if m == `Sofa.Check then continue
      match ci with
      | .thmInfo _ => nThm := nThm + 1
      | _ => nOther := nOther + 1
      let axs ← liftCoreM <| collectAxioms n
      for a in axs do union := union.insert a
      if axs.any (fun a => !std.contains a) then bad := bad.push (n, axs)
  logInfo m!"theorems: {toString nThm}, other constants: {toString nOther}; union of axioms: {union.toList}; constants with other axioms: {toString bad.size} {bad.toList.take 5}"

#audit_all_sofa
